### ISSUE TITLE
“不会ML”的方案中，用于LORA微调NER model和SQL model的数据来源？

### ISSUE THREAD

**Issue by Swgj** [Tongyi-EconML/FinQwen#7]
请问图中显示的这几个数据集是怎么获得的？是GPT合成数据？还是有具体的数据集来源？因为这个数据集太适合比赛的任务了所以非常好奇，恳请不吝赐教
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/eff71fe4-1b92-4c27-be73-5763f1b0c52d">

**Comment by wisdom-pan** [comment]
我感觉是通过few shot让gpt生成的，试了一下gpt4o的效果可以得到类似的结果

**Comment by Swgj** [comment]
谢谢解答！🌹
